server:
  port: 9006

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5 
    leaseExpirationDurationInSeconds: 10


ribbon:
  ServerListRefreshInterval: 2000
  eureka:
    enabled: true